cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
spring:
  application:
    name: rest-with-SpringBoot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: Webverton123.
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    com.weverton: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true